### ISSUE TITLE
"next lint" fails if validation is based on NODE_ENV

### ISSUE THREAD

**Issue by web3cub** [t3-oss/t3-env#102]
As Next.js sets `NODE_ENV` to `production` when running `next lint`, the following example fails if the `NEXTAUTH_SECRET` isn't present in the local env file:

```typescript
NEXTAUTH_SECRET:
  process.env.NODE_ENV === "production"
    ? z.string().min(1)
    : z.string().min(1).optional(),
```

One option could be changing the `"lint": "next lint"` to `"lint": "NODE_ENV=development next lint"` and that works when linting the whole project, but likely will have issues using husky and lint-staged.

Is there any recommended solution? Or should the validations be skipped completely when running `next lint`?

**Comment by chungweileong94** [comment]
Does `next lint` run the env validation? Mind if you can create a repro?
To me, "code linting" suppose to only check the code pattern/standard etc, but not the logic like env validation.

**Comment by adbario** [comment]
> Does `next lint` run the env validation?

It does indeed, as the `env.mjs` is imported to `next.config.mjs` in [create-t3-app](https://github.com/t3-oss/create-t3-app/blob/next/cli/template/base/next.config.mjs#L5)

`next build` also runs the `next lint`, but that won't be an issue as `NODE_ENV` is correctly `production` when building.

This is simple to test by setting up a fresh t3-app, unfortunately I don't think codesandbox allows running npm scripts.

**Comment by chungweileong94** [comment]
Okay I see. It seems to me everything is working accordingly for t3-env. 
I only realized today that `NEXTAUTH_SECRET` is optional in development, but I think making it mandatory doesn't harm at all.

Doing `"lint": "NODE_ENV=development next lint"` works too, but might not good ideal tho, as I not sure if NextJS used `NODE_ENV=production` for any specific reason. 

I would suggest you to raise an issue in https://github.com/t3-oss/create-t3-app instead?

**Comment by juliusmarminge** [comment]
Might be good to do something like

```ts
// next.config.mjs
process.env.npm_lifecycle_thing_whatever_its_called !== "lint" && (await import("~/env.mjs"))
```

🤔

**Comment by chungweileong94** [comment]
> ```ts
> process.env.npm_lifecycle_thing_whatever_its_called !== "lint" && (await import("~/env.mjs"))
> ```

@web3cub  Actually, you can do this `skipValidation: process.env.npm_lifecycle_event === 'lint'`
