### ISSUE TITLE
Refactor Documentation with Contentlayer Integration

### ISSUE THREAD

**Issue by SameerJadav** [t3-oss/t3-env#105]
Currently, docs are using `next/mdx` which makes the file structure complicated with `docs/slug/page.mdx`. I don't think this is the best way to organize our documentation.

To fix this, I suggest we use [Contentlayer](https://contentlayer.dev) instead. This will give us a lot of benefits, like:

- Validation
- Type-safety
- A cleaner codebase
- A better developer experience
- Custom SEO (head) for each document

Currently, we are limited to using the same head for each document, which is not ideal for SEO. With Contentlayer, we can have a head for each document, which will improve SEO.

I believe this change will be very helpful for the project. If the maintainers agree, I am willing to start working on it. Thank you for considering my proposal.

**Comment by juliusmarminge** [comment]
Contentlayer seems a bit overkill for the few pages we have. There are simpler solutions for the problems you've outlined:

- `Validation`: You can make a simple script and import it in `next.config.js` to validation metadata during build time. I do a similar thing for my personal page.
- `Type-safety`: Not sure what you mean by type-safety. Afaik, you don't get for example autocompletion or typeerrors with Contentlayer, just runtime/buildtime errors if your frontmatter doesn't match.
- `A cleaner codebase`: Depends how you look at things I guess?? It's more setup for the limited benefit we'd get.
- `Custom SEO for each document`: You can export a `metadata` variable in a `page.mdx` just as you can for `layout.tsx` or `page.tsx` to set SEO tags
