### ISSUE TITLE
environment variables should be read-only, but they are not

### ISSUE THREAD

**Issue by Zamiell** [t3-oss/t3-env#108]
Consider the following code:

```ts
export const env = createEnv({
  server: {
    PORT: z.number().default(80),
  }
});

env.PORT = 123; // Works??? WTF
```

Assignment here should throw an error from the TypeScript compiler, since we don't want to modify environment variables at runtime. If mutations are actually required, then they should be done using actual new TypeScript variables. (This is basically the same rationale as preferring to use `const` to make new variables over `let` if possible. In fact, by naming the properties of the object as uppercase, you are violating the mutability contract that TypeScript users expect when seeing uppercase variables/properties.)

I think submitting a PR for this should be pretty straightforward if you want me to do that, we just need to use the `Readonly` utility type.

**Comment by juliusmarminge** [comment]
sure!
