### ISSUE TITLE
Validate later

### ISSUE THREAD

**Issue by staff0rd** [t3-oss/t3-env#114]
I'd like to do something like `const env = createEnv({ skipValidation: false })` and then later, only in a specific circumstance, validate it.

My first thought to doing this was to do something like:

```typescript
const schema: Parameters<typeof createEnv>[0] = { 
    /* my env vars */,
    skipValidation: true,
}
const env = createEnv(schema)
const validateEnv = () => createEnv({...schema, skipValidation: false});
```

But doing this makes the type checking for `schema` very poor. 

Another approach could be to expose some `env.validate()` or similar, but I have not yet checked source to see whether this is possible.

Is there a better way share the schema across `createEnv` invocations while retaining good type checks?

**Comment by chungweileong94** [comment]
I'm quite curious that in what user case where you want to defer the validation?

**Comment by staff0rd** [comment]
My bad - easy approach staring me in the face:

```typescript
const buildEnv = (skipValidation = true) => createEnv({...schema, skipValidation});
export const env = buildEnv();
export const validateEnv = () => buildEnv(false);
```

**Comment by staff0rd** [comment]
@chungweileong94 I like the type checking, but I don't want the application to crash if an environment variable is invalid (as there's a chance that particular env might not yet be in an executable path accessible to the user).

Instead, I will call `validateEnv` by some CI process or similar.

**Comment by staff0rd** [comment]
Although, as I now see, this approach removes the `transform` & `default` capabilities on `skipValidation: true` too.

**Comment by chungweileong94** [comment]
> Although, as I now see, this approach removes the `transform` & `default` capabilities on `skipValidation: true` too.

Yes, the purpose of `skipValidation` is mostly for cases like skipping validation during unit testing. I would say those features are provided by zod instead of t3-env, pros and cons.
