### ISSUE TITLE
runtimeEnvStrict doesn't type check for missing variables in @t3-env/core when no client prefix set

### ISSUE THREAD

**Issue by johnslemmer** [t3-oss/t3-env#117]
I was trying to use @t3-env/core for an unsupported framework. However, `runtimeEnvStrict` doesn't throw any type errors as I would expect.

This will *not* produce an error
```js
import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  skipValidation: !!process.env.CI,
  runtimeEnvStrict: {
    // NODE_ENV: process.env.NODE_ENV,
  },

  server: {
    NODE_ENV: z.enum(["development", "test", "production"]),
  },
});
```

The workaround is to include a client prefix and at least an empty client object to get things to work.  The following *does* show an error for `runtimeEnvStrict`:

```js
import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  clientPrefix: "FOO",
  skipValidation: !!process.env.CI,
  runtimeEnvStrict: {
    // NODE_ENV: process.env.NODE_ENV,
  },

  server: {
    NODE_ENV: z.enum(["development", "test", "production"]),
  },

  client: {},
});

```

I know the typing around this is quite complicated. So maybe the work around is this best way to make it work. Hope this is useful for anyone else.

**Comment by chungweileong94** [comment]
Interesting🤔 I will take a look once I free to do so.
