### ISSUE TITLE
Throws error when trying to use Vercel's edge runtime config

### ISSUE THREAD

**Issue by sebpowell** [t3-oss/t3-env#124]
Hi there, 

First of all, thank you for this library – it's been great to work with. I'm not entirely sure this is a bug, but wanted to ask for advice. 

I'm currently using Next.js 13 with the app directory, but API routes are still using the pages directory (reason being that I am using TS-Rest, and as far as I'm aware, it currently only works with the pages directory). I wanted to try and enable Vercel's edge functions – which according to the documentation (see [here](https://vercel.com/docs/functions/edge-functions)) should be enabled in the following way:

```TSX
// pages/api/[...ts-rest].tsx

import { createNextRoute, createNextRouter } from '@ts-rest/next';

export const config = {
  runtime: 'edge',
};

const router = createNextRoute(contracts, {
});

const nextApiRouter = createNextRouter(contracts, router);

export default nextApiRouter;

```

When I try running the app, t3-env throws an error due to missing environment variables (which are defined). The variables it complains about are all those that are specified in the server key, which in my case are the following:

```TS
export const env = createEnv({
  server: {
    STRIPE_SECRET_KEY: z.string(),
    NEXT_CONTENTFUL_SPACE_ID: z.string(),
    NEXT_CONTENTFUL_ENVIRONMENT: z.string(),
    NEXT_CONTENTFUL_CONTENT_DELIVERY_KEY: z.string(),
  },
});
```

I'm guessing I need to make these available to the runtime environment, but then doesn't that risk exposing the secrets? Any advice gratefully received.

**Comment by juliusmarminge** [comment]
What Next.js version?

In previous versions, you have to destruct the object manually to avoid them being "treeshaken" away at build time.

In more recent versions this step is only necessary for client side variables.

Ref: https://env.t3.gg/docs/nextjs#create-your-schema

**Comment by juliusmarminge** [comment]
Closing as stale. If the above didn't help feel free to reopen with a reproduction
