### ISSUE TITLE
feat: `@t3-oss/env-svelte`

### ISSUE THREAD

**Issue by juliuslipp** [t3-oss/t3-env#125]

**Comment by chungweileong94** [comment]
I don't have much experience with Svelte, but good news is you should able to use it with the core package https://env.t3.gg/docs/core. 🙂
Both Next.js & the Nuxt packages are nearly identical to the core, but with some options pre-configured that's all.

**Comment by juliusmarminge** [comment]
Sure, feel free to submit a PR! 

But you can always use the core and add the few extra options yourself too if you want to use it today

**Comment by juliusmarminge** [comment]
Going to close it as noone else has requested it and i think using the core package will be just as fine
