### ISSUE TITLE
This support different .env files like .env.production or .env.development?

### ISSUE THREAD

**Issue by MiniSuperDev** [t3-oss/t3-env#128]
Like [vite env files](https://vitejs.dev/guide/env-and-mode.html#env-files), or for example for express app, to load different files based on NODE_ENV

Thanks

**Comment by chungweileong94** [comment]
@MiniSuperDev t3-env only handle env validation, but doesn't handle env file load. It's up to how the framework (Site, NextJS, etc) loads the env file.
