### ISSUE TITLE
Invalid environment variables error with next build and app directory

### ISSUE THREAD

**Issue by teddybee** [t3-oss/t3-env#129]
I have got this error, I have only one server side variable. .env file is in the project`s root dir.
```
Collecting page data  ...❌ Invalid environment variables: { BACKEND_URL: [ 'Required' ] }
Error: Invalid environment variables

> Build error occurred
Error: Failed to collect page data for /api/auth/[...nextauth]
    at D:\NodeJS\***\next-frontend\node_modules\.pnpm\next@13.5.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\utils.js:1178:15
```
I have used the env object in the next-auth`s api route, inside app directory.
"@t3-oss/env-nextjs": "^0.6.1",
"next": "^13.5.3",
pnpm: 8.8.0
NodeJS: 20.8.0
Windows 11

**Comment by chungweileong94** [comment]
Could you provide a repro, there could be some configurations problem in your codebase.

**Comment by LandSprutte** [comment]
Running into the same problem :) any news on this?

**Comment by teddybee** [comment]
@chungweileong94 The problem was this: It cannot read the data from .env variable. When I removed the dependency from t3env package (process.env.***) the app built successfully again.

Anyway, I couldn`t reproduce the problem with new 14.0.2 nextjs app and "@t3-oss/env-nextjs": "^0.7.1".
Works as expected.
