### ISSUE TITLE
TS2345: `emptyStringAsUndefined`  does not exist in type, in 0.7.0

### ISSUE THREAD

**Issue by ari-becker** [t3-oss/t3-env#135]
Copy-pasting from the documentation:

![image](https://github.com/t3-oss/t3-env/assets/1388505/3c61c45c-a0d5-4e8b-958a-af5adce49be9)
![image](https://github.com/t3-oss/t3-env/assets/1388505/2368e5fb-41e8-4552-999a-df284f64c0ed)

I've double-checked that I did indeed update to `0.7.0`.

**Comment by juliusmarminge** [comment]
hmm cannot seem to reproduce that, would you mind posting a repro?

![CleanShot 2023-10-16 at 08 55 20@2x](https://github.com/t3-oss/t3-env/assets/51714798/480a5ba1-39c7-48d2-9e99-36ee85971068)

**Comment by juliusmarminge** [comment]
Try 0.7.1 as well, I don't think it solved your issue but I moved the option to the base options in #138 which might have a difference

**Comment by ari-becker** [comment]
> Try 0.7.1 as well, I don't think it solved your issue but I moved the option to the base options in #138 which might have a difference

@juliusmarminge yes, this fixed it for me! Thanks.
