### ISSUE TITLE
Importing from env.mjs in next project leads to infinite loading of typescript intellisense

### ISSUE THREAD

**Issue by chribjel** [t3-oss/t3-env#136]
When importing from "@/env.mjs"  typescript get reeaaally slow. It takes more than a minute to load intellisense.

Files where no env-variables are imported seems to be working fine

`"@t3-oss/env-nextjs": "0.7.0"`

VSCode:
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by juliusmarminge** [comment]
Interesting... can you provide a repro where this happens?

I got a fairly large ts project with a big env.mjs file and haven't noticed this issue.

**Comment by chribjel** [comment]
> Interesting... can you provide a repro where this happens?
> 
> I got a fairly large ts project with a big env.mjs file and haven't noticed this issue.

Will try to provide a minimal repro this week.

**Comment by juliusmarminge** [comment]
Closing as stale. Feel free to re-open with a reproduction repo.
