### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by benjick** [t3-oss/t3-env#137]
Hello!

Really like this library, but there is possibly something weird happening with it. My intellisense in vscode grinds to a halt, and if I open my env.mjs-file I see this error: 
<img width="654" alt="Screenshot 2023-10-14 at 09 08 49" src="https://github.com/t3-oss/t3-env/assets/430872/305af6c9-aaa9-48f0-8492-6536babb9930">

Sometimes I can comment out all/some of the env vars and it will stop, then when I uncomment them it seems to work a while, like it takes some time for intellisense to actually get stuck. Sorry for being vague, I'm not even 100% sure the issue in this plugin, but this is the only file I've seen acting weird so far.

I've tried naming it both .ts and .mjs

This is the full code:

```ts
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  /**
   * Specify your server-side environment variables schema here. This way you can ensure the app
   * isn't built with invalid env vars.
   */
  server: {
    DATABASE_URL: z.string().url(),
    REDIS_HOST: z.string().default("localhost"),
    REDIS_PORT: z.coerce.number().default(6379),
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    GOOGLE_REDIRECT_URI: z
      .string()
      .url()
      .default("http://localhost:3000/login/google/callback"),
    OPENAI_API_KEY: z.string(),
    OPENAI_ORG: z.string().optional(),
    PLAUSIBLE_API_KEY: z.string().optional(),
    MEILI_MASTER_KEY: z.string(),
    MEILI_HOST: z.string(),
  },

  /**
   * Specify your client-side environment variables schema here. This way you can ensure the app
   * isn't built with invalid env vars. To expose them to the client, prefix them with
   * `NEXT_PUBLIC_`.
   */
  client: {
    NEXT_PUBLIC_PLAUSIBLE_DOMAIN: z.string().min(1).default("localhost"),
    NEXT_PUBLIC_MEILISEARCH_URL: z
      .string()
      .min(1)
      .default("http://localhost:7700"),
  },

  /**
   * You can't destruct `process.env` as a regular object in the Next.js edge runtimes (e.g.
   * middlewares) or client-side so we need to destruct manually.
   */
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    REDIS_HOST: process.env.REDIS_HOST,
    REDIS_PORT: process.env.REDIS_PORT,
    NODE_ENV: process.env.NODE_ENV,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_ORG: process.env.OPENAI_ORG,
    PLAUSIBLE_API_KEY: process.env.PLAUSIBLE_API_KEY,
    MEILI_MASTER_KEY: process.env.MEILI_MASTER_KEY,
    MEILI_HOST: process.env.MEILI_HOST,

    NEXT_PUBLIC_PLAUSIBLE_DOMAIN: process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN,
    NEXT_PUBLIC_MEILISEARCH_URL: process.env.NEXT_PUBLIC_MEILISEARCH_URL,
  },
  /**
   * Run `build` or `dev` with `SKIP_ENV_VALIDATION` to skip env validation. This is especially
   * useful for Docker builds.
   */
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
```

**Comment by juliusmarminge** [comment]
Can you reproduce this elsewhere? I've never seen this and even with your env file copied into a large ts project i don't get any errors. What does your tsconfig look like?

**Comment by chribjel** [comment]
Seems similar to #136

**Comment by joachimjusth** [comment]
I had exactly the same issue on my project.

I solved it via clearing my node_modules and removing my lock file and made a fresh install.
I also upgraded to the latest version of zod (was on 3.21.4 during the issue).

Now everything is ok on my side (local and deployment).

Fyi I'm using now:

- bun 1.0.2
- @t3-oss/env-nextjs 0.7.1
- zod 3.22.4

Before:

- bun 1.0.2
- @t3-oss/env-nextjs 0.7.0
- zod 3.21.4

**Comment by Eltik** [comment]
Thank you! I have the same issue. Downgrading seems to have fixed this. Seems to be similar to [this](https://github.com/t3-oss/t3-env/issues/136) to.

**Comment by matheins** [comment]
I saw the same in my project, when using a env.mjs in a turbo repo's package.

**Comment by juliusmarminge** [comment]
Closing as stale. Feel free to re-open with a reproduction repo.
