### ISSUE TITLE
consider allowing `string | boolean | undefined` for `runtimeEnvStrict`

### ISSUE THREAD

**Issue by stefanprobst** [t3-oss/t3-env#14]
when using this package with `nuxt` to type `VITE_` env vars, i am running into the following issue: `nuxt` types `import.meta.env` as `Record<string, string | boolean | undefined>` (see [here](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/types/global/index.ts#L11)) - i am guessing because `vite` sets [these](https://github.com/vitejs/vite/blob/main/packages/vite/types/importMeta.d.ts#L7-L14) default values. however, `t3-env` enforces `runtimeEnvStrict` to be `Record<string, string | undefined>`. would you consider allowing `Record<string, string | boolean | undefined>` on `runtimeEnvStrict` to cover this usecase?

**Comment by juliusmarminge** [comment]
That's a strange one - never seen that... environment variables are usually just strings...

I guess it'd fine? Although would love to know why this typedefinition is what it is to begin with 🤔

**Comment by chungweileong94** [comment]
From what I can tell, it's no longer the case https://github.com/vitejs/vite/pull/7702 in `vite`. 
There're only two possible reasons I can think of: 

- it's either `nuxt` team forgot to fix the type.
- `nuxt` has some sort of parser for parsing the boolean-like values.

**Comment by chungweileong94** [comment]
TBH, I don't think it's a bad idea to define the type as `any`, since it has `runtimeEnv` config, which means the value can be anything other than `process.env`, plus it's all about zod validation anyway.

**Comment by juliusmarminge** [comment]
i guess
