### ISSUE TITLE
How to correctly setup DEV ENV Variables

### ISSUE THREAD

**Issue by EricBatlle** [t3-oss/t3-env#141]
Hey, I've 2 .env files:
```
.env
.env.development
```

If I use the command "npm run dev" it will read first .env.development and then .env (which is correct).

Now I want to create a command like "npm run dev2" that will **ONLY** read **.env**, without .env.development.
I've tried to modify package.json with:

```
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "postinstall": "prisma generate",
    "lint": "next lint",
    "start": "next start",
    "dev2": "NODE_ENV=production npm run dev"     <----- This is the addition!
  },
```

But when I use the command npm run dev2, it says that "NODE_ENV is not recognized as internal or external command."

How should I proceed? Thanks!

**Comment by juliusmarminge** [comment]
are you on windows? if so i think you should do 

```json
    "dev2": "set NODE_ENV=production npm run dev"
```

**Comment by EricBatlle** [comment]
I've tried but it doesn't work (instantly closes the process without any further message).

With your comment I've tried to do:  
`"dev2": "set NODE_ENV=production && npm run dev"`

But it gives me the following error:
![image](https://github.com/t3-oss/t3-env/assets/15261880/fcbc405a-204c-423b-a864-b2b03c896a2f)

I also tried to do:
`"dev2": "set NODE_ENV='production' && npm run dev"`
But then it gives me the following error:
![image](https://github.com/t3-oss/t3-env/assets/15261880/16dff0ca-2a15-41f8-b796-173b83f0a10e)

Any idea? :(

**Comment by chungweileong94** [comment]
@EricBatlle `set XXX=xxx` is actually Windows CMD way of setting env variable in command-scope, which it doesn't work well with PowerShell based on my past experience. 

You can either do `set NODE_ENV=production&& npm run dev` (this will avoid the trailing space), or better, do `$env: NODE_ENV="production" ; npm run dev` instead.
 
You could use package like `env-cmd`, it works across different platforms.

**Comment by juliusmarminge** [comment]
Or use cross-env: https://github.com/kentcdodds/cross-env

**Comment by EricBatlle** [comment]
> @EricBatlle `set XXX=xxx` is actually Windows CMD way of setting env variable in command-scope, which it doesn't work well with PowerShell based on my past experience.
> 
> You can either do `set NODE_ENV=production&& npm run dev` (this will avoid the trailing space), or better, do `$env: NODE_ENV="production" ; npm run dev` instead.
> 
> You could use package like `env-cmd`, it works across different platforms.

As in my last comment, using `set NODE_ENV=production&& npm run dev` gives me the error:
![image](https://github.com/t3-oss/t3-env/assets/15261880/8a63e4aa-5599-4916-803a-4bc228914e22)
