### ISSUE TITLE
Remove misleading boolean coercing example from docs?

### ISSUE THREAD

**Issue by JonasDoesThings** [t3-oss/t3-env#143]
Hi, I noticed the docs (https://env.t3.gg/docs/recipes#booleans) contain the following example for boolean coercion
```
...
// Alternatively, use Zod's default primitives coercion
// https://zod.dev/?id=coercion-for-primitives
ZOD_BOOLEAN_COERCION: z.coerce.boolean(),
```

In my opinion this should not be recommended, since zod boolean coercion uses the [`Boolean(str)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean) function under the hood.
This function always returns `true` for every string passed:

```
Boolean("false");
> true
Boolean("0")
> true
Boolean("fsajiosdaisj")
> true
```
Since env variables are all loaded as strings, this method always returns true, no matter the environment variable's value.

So while the docs are *technically* correct - everyone without knowledge about this behavior would assume that the env variable "false" would get coerced to boolean false. This could lead to wrong and insecure behavior for the end-user.

Related zod issue: https://github.com/colinhacks/zod/issues/1630

I would be ok with filing a PR myself for this, but wanted to hear other opinions first.

**Comment by chungweileong94** [comment]
Yeah agree, I think that should be removed. 
`true` is true, `false` is false, I don't see a reason why we need `false` -> true😅

**Comment by JonasDoesThings** [comment]
> Yeah agree, I think that should be removed. `true` is true, `false` is false, I don't see a reason why we need `false` -> true😅

Great, I've filed PR #145 regarding this.
Thanks again for maintaining this awesome package :)

**Comment by JonasDoesThings** [comment]
Closing due to PR having been merged.
