### ISSUE TITLE
Add nextjs instrumentation suggestion

### ISSUE THREAD

**Issue by V1RE** [t3-oss/t3-env#147]
Recently saw [this tweet](https://x.com/ErfanEbrahimnia/status/1723741584984846532), would this be an interesting addition to the nextjs part of the docs? Would mean you could still keep your files with a .ts extension instead of changing it to mjs

**Comment by chungweileong94** [comment]
Haven't try with it myself, but according to the docs, it runs when a new Next server instance is bootstrapped, which doesn't seem to be a good alternative tho, but I have to try it myself.

**Comment by juliusmarminge** [comment]
use jiti instead. instrumentation is not what this is for
