### ISSUE TITLE
Type 'ZodString' is not assignable to type '`DATABASE_URL should not prefixed with ${string}.`'

### ISSUE THREAD

**Issue by samyarkd** [t3-oss/t3-env#151]
I have been getting this error bellow, i can't assign Zod type to a variable only in the server part the client works fine. 

```
Type 'ZodString' is not assignable to type '`DATABASE_URL should not prefixed with ${string}.`'.ts(2322)
server.ts(9, 5): The expected type comes from property 'DATABASE_URL' which is declared here on type 'Partial<{ DATABASE_URL: `DATABASE_URL should not prefixed with ${string}.`; BOT_TOKEN: `BOT_TOKEN should not prefixed with ${string}.`; NETWORK: `NETWORK should not prefixed with ${string}.`; TON_API_KEY: `TON_API_KEY should not prefixed with ${string}.`; TON_API_ENDPOINT: `TON_API_ENDPOINT should not prefixed with ...'
```

![image](https://github.com/t3-oss/t3-env/assets/75088294/d03271ac-dc4f-4272-a71d-5475b52bcd1a)

My config:
```
NextJs: 14.0.3,
@t3-oss/env-core: 0.7.1
NX: 17.1.3
```

**Comment by chungweileong94** [comment]
Could you provide a repo for this issue? It feels like a TS config problem, but it can be other reasons as well.

**Comment by asobirov** [comment]
+1

**Comment by Poudlardo** [comment]
![Capture d'écran 2024-01-23 102940](https://github.com/t3-oss/t3-env/assets/55178305/fdb20089-49aa-44e2-9226-cf69d1fc7b76)
 Having the same issue with 'NEXT_PUBLIC' string

**Comment by Just-Moh-it** [comment]
@Poudlardo mind updating your original comment with the env.mjs file and your t3-env version?

**Comment by Poudlardo** [comment]
@Just-Moh-it I put my t3-env version. I can't import env.mjs file though, github don't support the format

**Comment by juliusmarminge** [comment]
@Poudlardo Just remove the NEXT_PUBLIC variable from the server section. NEXT_PUBLIC are client vars

![CleanShot 2024-01-24 at 12 34 41@2x](https://github.com/t3-oss/t3-env/assets/51714798/f8d63754-535b-46ca-a78a-ddef6aafbf6a)

**Comment by Poudlardo** [comment]
Basically [I was following that guy ](https://youtu.be/TV6tFPfz0go?si=_pd9B7OKDcrr-90C&t=3553) who would put NEXT_PUBLIC_ prefix on server, client and runtime environment objects. And it works for him.

But I deleted it. Hope it doesn't lead to later problems.
Thanks

**Comment by ashphy** [comment]
Try to enable the `strict` or `strictNullChecks` option in your tsconfig.json.

**Comment by cloudbring** [comment]
> Try to enable the `strict` or `strictNullChecks` option in your tsconfig.json.

`"@t3-oss/env-core": "^0.12.0"`
`"zod": "^3.24.1"`
`"typescript": "^5.7.3"`
`"ts-node": "^10.9.2"`

**`tsconfig.json`**
```json
{
  "ts-node": {
    "files": true
  },
  "compilerOptions": {
    "target": "es2018",
    "lib": ["es2018", "DOM"],
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strictNullChecks": false,
    "types": ["codeceptjs", "node"],
    "declaration": true,
    "skipLibCheck": true
  },
  "exclude": ["node_modules"]
}

```

VSCode Version: 1.95.2


I had this issue and can verify that changing `strictNullChecks` from `false` to `true` fixed the issue in VSCode for me.

**Comment by samyarkd** [comment]
> Try to enable the `strict` or `strictNullChecks` option in your tsconfig.json.

This worked for me.

**Comment by expl0r3rgu1** [comment]
> [@Poudlardo](https://github.com/Poudlardo) Just remove the NEXT_PUBLIC variable from the server section. NEXT_PUBLIC are client vars
> 
> ![CleanShot 2024-01-24 at 12 34 41@2x](https://github.com/t3-oss/t3-env/assets/51714798/f8d63754-535b-46ca-a78a-ddef6aafbf6a)

Thanks man 🙏
