### ISSUE TITLE
isServer detection faulty when jsdom is present

### ISSUE THREAD

**Issue by merk** [t3-oss/t3-env#154]
My testing environment installs jsdom which sets a window global - meaning that all tests run as a client according to t3-env.

My initial reaction is to override the isServer check to something like [this solution](https://github.com/jsdom/jsdom/issues/1537#issuecomment-1689368267) mentioned on the jsdom repo.

It feels like an acceptable solution (and I'm happy to send a PR) but I'm not 100% sure if the change is a good one?

https://github.com/t3-oss/t3-env/blob/63a7fed1cb85e05d59c1c3c87e5b434cc8a353cc/packages/core/index.ts#L202C37-L202C66

**Comment by chungweileong94** [comment]
This actually make t3-env support Deno out of the box, so why not🤷

The only question is how reliable is this `Object.getOwnPropertyDescriptor(globalThis, 'window')?.get?.toString().includes('[native code]') ?? false`, but it works pretty good on environment like NodeJS, Bun, Deno, Arc(Chromium), Safari.

**Comment by juliusmarminge** [comment]
I'd say this is an app-concern and you should use the option to override the default behavior. We can't cover every case by default and I think `typeof window === "undefined"` is the most well-known and used option out there

**Comment by juliusmarminge** [comment]
Hmm looks like we use a slightly more covering one in trpc so maybe?

https://github.com/trpc/trpc/blob/next/packages/server/src/unstable-core-do-not-import/rootConfig.ts#L18

**Comment by yogarasu** [comment]
This option is necessary when testing with Storybook because server-side variables used in Next.js server actions become an issue since they are rendered client-side.

**Comment by juliusmarminge** [comment]
Feel free to extend the default isServer check to something that covers more runtimes

**Comment by michaellopez** [comment]
I added detection of Deno as server in #220 (Netlify uses Deno to bundle Next.js for edge)

For those coming here for a workaround until #220 is merged can add this to `createEnv(...)` call for server environment:

`isServer: typeof window === "undefined" || "Deno" in window,`

e.g.

```
export const env = createEnv({
  isServer: typeof window === "undefined" || "Deno" in window,
  server: {
    ...
  }
  ...
```
