### ISSUE TITLE
Version 0.7.2 not installable

### ISSUE THREAD

**Issue by paleite** [t3-oss/t3-env#164]
Installing the latest version (0.7.2) via pnpm (8.14.0) doesn't work, but 0.7.1 works fine:

```
pnpm add @t3-oss/env-nextjs
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@t3-oss/env-core@workspace:*" is in the dependencies but no package named "@t3-oss/env-core" is present in the workspace

This error happened while installing the dependencies of @t3-oss/env-nextjs@0.7.2

Packages found in the workspace: 
Progress: resolved 13, reused 13, downloaded 0, added 0
```

**Comment by dashmedialtd** [comment]
Currently experiencing the same issue, but with yarn:

```Error: @t3-oss/env-core@workspace:*: Workspace not found (@t3-oss/env-core@workspace:*)```

**Comment by lluchkaa** [comment]
@juliusmarminge I think it cannot be installed because of the workspace specifier.

Commit [e712ef36b1b56a929ea1bdd527fd39ab5952c2f0](https://github.com/t3-oss/t3-env/commit/e712ef36b1b56a929ea1bdd527fd39ab5952c2f0)

**Comment by juliusmarminge** [comment]
Oh what? The workspace specifier should be replaced during release??? I’ll have a look when i get home

**Comment by lluchkaa** [comment]
> Oh what? The workspace specifier should be replaced during release??? I’ll have a look when i get home

Yeah, I think when installing `@t3-oss/env-nextjs` packages, it wants to install dependencies of this package as well and cannot find it because there're no one in workspace

**Comment by juliusmarminge** [comment]
Yes, I get that. But the code on npm shouldn't have that at all, but it does: ![image](https://github.com/t3-oss/t3-env/assets/51714798/0d65e9a4-f142-4947-a007-02b64928a7d9)

So I'll have to look why it's not replaced during publish

**Comment by lluchkaa** [comment]
What tool do you use to publish package? I believe it was `pnpm`, but you're migrating to `bun`.
I can see that pnpm replaces this specifier.

<img width="677" alt="Screenshot 2024-01-12 at 15 04 19" src="https://github.com/t3-oss/t3-env/assets/37471864/a7e84fd1-6035-4b26-b9eb-46e58100971f">

**Comment by juliusmarminge** [comment]
Changeset

**Comment by bel7aG** [comment]
same on yarn, it's blocking feature releases (Vercel failing to install)

**Comment by ibqn** [comment]
same here, this release is broken and can't be installed

**Comment by juliusmarminge** [comment]
Should be fixed now. Sorry
