### ISSUE TITLE
Investigate Jiti usage instead of having .mjs files?

### ISSUE THREAD

**Issue by mastondzn** [t3-oss/t3-env#166]
[Jiti](https://github.com/unjs/jiti/) allows you to import straight typescript during runtime, i believe this could be beneficial here especially since you could import a "env" monorepo package in next's config file without having to compile it.

This wouldn't change any api of this package, just have to document this usage if it is deemed useful.

```js
// next.config.mjs
import { fileURLToPath } from 'node:url';
import jiti from 'jiti';

const filename = fileURLToPath(import.meta.url);

// ./src/env.ts can be typescript!
const envPath = './src/env'
// .. or with a uncompiled, raw ts monorepo package!
const envPath = fileURLToPath(import.meta.resolve('@acme/env'));

jiti(filename)(envPath);

/** @satisfies {import("next").NextConfig} */
const config = {
    // ...
};

export default config;
```

**Comment by deadcoder0904** [comment]
can confirm.

i imported my `env.ts` file like this:

```ts
import './src/app/lib/env' // would also like `import '@/src/app/lib/env'` to be supported
```

and got this error:

> Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'E:\nextjs-rate-limit\src\app\lib\env' imported from E:\nextjs-rate-limit\next.config.mjs

used `jiti` by [searching on sourcegraph](https://sourcegraph.com/search?q=context:global+%40t3-oss/env-nextjs+AND+/env+lang:TypeScript+&patternType=standard&sm=0), found [this](https://sourcegraph.com/github.com/tszhong0411/honghong.me@09d57d6c31654d31de6ecfd4167e7631d87dc471/-/blob/next.config.mjs) & the error was gone.

#### next.config.mjs

```mjs
import jiti from 'jiti'
import { fileURLToPath } from 'node:url'

const filename = fileURLToPath(import.meta.url)
const envPath = './src/app/lib/env'

jiti(filename)(envPath)

/** @type {import('next').NextConfig} */
const nextConfig = {}

export default nextConfig
```
