### ISSUE TITLE
env type is not inferred so no autocomplete.

### ISSUE THREAD

**Issue by adeleke5140** [t3-oss/t3-env#168]
I have my `env.mjs` file in a NextJS `13.4.19` project using the `app` directory. It is a monorepo setup with `pnpm` workspaces.

The inferred type in the `env.mjs` file is:

```
Readonly<{
    [x: string]: any;
}>
```

When I hover over `createEnv`, I get this:

```
(alias) createEnv<{
    DATABASE_URL: z.ZodString;
}, {}, {}>(opts: Options<{
    DATABASE_URL: z.ZodString;
}, {}, {}>): Readonly<{
    [x: string]: any;
}>
import createEnv
```

And when I try to use the `env` in either `client` or `server`, none of the `env` variables show up because, I assume, env doesn't have the right type.

## What I have tried
1. Quit the editor and restarted it
2. Restarted the TS server
3. Reinstalled `t3-oss`
4. Checked the `ts-config`

## Details:

Version
`@t3-oss/env-nextjs": "^0.7.3"`

**Comment by juliusmarminge** [comment]
Thank you for filing this issue, unfortunately we don't have time to investigate issues without a reproduction.

We have tests in place to ensure types are working as expected, so this is likely something specific to your setup, perhaps a TypeScript version, tsconfig option etc. Feel free to re-open with a public reproduction repository and we can look into it for you.

**Comment by sitch** [comment]
Same issue here -- stick to v0.7.1

**Comment by deadcoder0904** [comment]
can confirm. happened after latest update on `^0.9.2`. works fine in `^0.9.1` in my main project.

![image](https://github.com/t3-oss/t3-env/assets/16436270/72824181-2f04-43cd-ac3c-1b608707066b)

but it works fine in my newly created repro of a new next.js project -> https://github.com/deadcoder0904/drizzle-t3-oss-env

i tried clearing pnpm cache & reinstalling everything all over again but nothing.

**Comment by juliusmarminge** [comment]
> can confirm. happened after latest update on `^0.9.2`. works fine in `^0.9.1` in my main project.
> 
> ![image](https://private-user-images.githubusercontent.com/16436270/303340490-72824181-2f04-43cd-ac3c-1b608707066b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDEzMzcsIm5iZiI6MTcwNzQwMTAzNywicGF0aCI6Ii8xNjQzNjI3MC8zMDMzNDA0OTAtNzI4MjQxODEtMmYwNC00M2NkLWFjM2MtMWI2MDg3MDcwNjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE0MDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYmZmNTMyZjFiN2M2MTdjYTJhNmYxMGU2OGMyZTU0ZDVjYzFiYzM3Y2NiMjZmNTc3MzFkNjExMDI5NGFmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RKQpTBvM9f81asv3sUi2tDOMXdDuTPAwD1_CiIWiS64)
> 
> but it works fine in my newly created repro of a new next.js project -> https://github.com/deadcoder0904/drizzle-t3-oss-env
> 
> i tried clearing pnpm cache & reinstalling everything all over again but nothing.

This seems to work?

![CleanShot 2024-02-08 at 15 05 36@2x](https://github.com/t3-oss/t3-env/assets/51714798/0e5e55de-b3de-4c4a-8d6b-28882c8d5669)

**Comment by deadcoder0904** [comment]
yeah, this one works. i was creating bug repro for the other issue.

but my main project doesn't for some weird reason.

**Comment by juliusmarminge** [comment]
if you can give me access i can take a quick look and see if i find anything immediate

**Comment by deadcoder0904** [comment]
naah, access is not allowed but i'm pretty sure you should get more issues on this. should be common.

i also found this:

https://github.com/t3-oss/t3-env/issues/180#issuecomment-1935313862

^0.9.1 gives type inference but ^0.9.2 gives any type.

^0.9.1 still gives error mentioned in the linked issue when i run `pnpm db:generate` so it can't be ran anyways.

**Comment by EilifAkerjordet** [comment]
Hey! I had the exact same issue. What ended up solving to for me was upgrading zod to the latest version.
