### ISSUE TITLE
Vercel preset in `@t3-oss/env-nextjs` should include `NEXT_PUBLIC_VERCEL_*` variables

### ISSUE THREAD

**Issue by ronanru** [t3-oss/t3-env#175]
Just updated to the 0.8.0 version and added a vercel preset on my nextjs project. Unfortunately, I found that the preset only includes server-side vercel env variables. Can you also include client-side vercel variables in the nextjs package (https://vercel.com/docs/projects/environment-variables/system-environment-variables#framework-environment-variables)? I want to use NEXT_PUBLIC_VERCEL_ENV and NEXT_PUBLIC_VERCEL_URL, but have to add them separately.

I'd be happy to make a PR!

**Comment by 3kumar** [comment]
@ronanru  How did you manage to import presets from '@t3-oss/env-nextjs'. 

Trying to import the following way, but it is not resolved. 

`import { vercel } from "@t3-oss/env-nextjs/presets";`

Do I need to install env-core and import preset from there?

**Comment by ronanru** [comment]
You need `"moduleResolution": "Bundler",` in tsconfig probably @3kumar

**Comment by juliusmarminge** [comment]
actually the NEXT_PUBLIC_* are only avaiable during buildtime so i think it's kind of an antipattern if you use those variables in your app since they'll be undefined for 99% of cases, so I don't want to include them since it would only introduce confusion
