### ISSUE TITLE
Receiving "'?' expected" at build with an older version of typescript

### ISSUE THREAD

**Issue by nicholascostadev** [t3-oss/t3-env#18]
Repro for this: [codesandbox-repro](https://codesandbox.io/p/sandbox/t3-env-issue-vk4nru)

PS: The reproduction is following the same package versions I'm using in the project I'm seeing this error

### How to reproduce

1. run `npm run dev` on terminal - Everything works fine, you can also check by removing from the `.env` and you will see that the errors will appear, so it's working as expected.
2. run `npm run build` on terminal - Errors as shown on the image below

### Conclusion

I can say it's a typescript version problem, I'm using `4.6.4` and it doesn't work, but the next stable version I've seen on the typescript changelog was `4.7.2` and it works fine. I don't really know what came new in this version or if it had a bug fix, but I think you should maybe say on Readme the minimum version of typescript required? I don't know if it's enough of proof, but seems like it stops breaking at `4.7.2`

I've checked agains these versions of typescript:

1. 4.7.3
2. 4.7.2
3. 4.6.4
4. 4.6.3
5. 4.6.2
6. 4.5.5
7. 4.5.4

Those versions before 4.7.2 seem to be broken.

![image](https://user-images.githubusercontent.com/86835927/234595345-4481d88b-8492-4b74-93f5-33fa72747768.png)

**Comment by juliusmarminge** [comment]
Thanks for opening.

I'll take a look and see if I use any fancy new modern stuff and if I do, try rewriting them in less modern options - or set a peerDependency 👍👍

**Comment by yazanabuashour** [comment]
I was able to reproduce the same issue using typescript 4.6.4 for both packages, env-core and env-nextjs.

**Comment by chungweileong94** [comment]
it's because of this [feature](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#extends-constraints-on-infer-type-variables) introduce in TS 4.7, and it's cause by the `z.infer<...>` in [here](https://github.com/t3-oss/t3-env/blob/5b7067bda25c62266b157018961c7ab7a37a7e73/packages/core/index.ts#L100), even doing this `z.object(...)['_output']` will cause the same issue.

I'm not super familiar with the tsup, but maybe we can build the code with the older TS version?

**Comment by juliusmarminge** [comment]
Eeh we can require 4.7 i think 🤔 thats 4 versions down

**Comment by chungweileong94** [comment]
> Eeh we can require 4.7 i think 🤔 thats 4 versions down

Yeah, agree.

**Comment by yazanabuashour** [comment]
I'm happy to make this change. I have a branch ready to be pushed. Can I have assignment to this issue please?
