### ISSUE TITLE
Multiple .env files in a monorepo

### ISSUE THREAD

**Issue by gokaygurcan** [t3-oss/t3-env#181]
Hi,

I was following #158 and it was promising, but after trying something similar with multiple folders and different scopes, I see that my approach is failing miserably. 

First and foremost, here's a very simplified example, if you want to take a look at it: https://codesandbox.io/p/devbox/ecstatic-pascal-wxcffg

## Problem

I've this structure (simplified):
```txt
- apps/
     next/
- packages/
     api/
- .env
```

Meaning, there's a global `.env` file at the root, that keeps ALL environment variables. And there're more than one -let's call them- sub-projects in the folder. `apps/next` has its own `env.mjs` file which is only interested in a certain part of the global env variables, same as `packages/api`. 

When I start the app, it's failing to find the .env from root directory and I don't really prefer copying or symlinking it to every single place. 

What would you suggest? Or am I doing it completely wrong? 

Note: in a real case, there're more apps and more packages, any suggestion needs to be able to scale in that sense. It's easy to manage 2-3 files manually, but not 10 or more.

**Comment by juliusmarminge** [comment]
```json
{
  "scripts": {
    "with-env": "dotenv -e ../../.env --",
    "build": "pnpm with-env next build"
  }
}
```

should work

**Comment by gokaygurcan** [comment]
Hi @juliusmarminge,

Thanks for your reply. 

I'm not sure about it. `packages/api` doesn't have any build step. This would work for `apps/next` for sure, and I tried similar things with dotenv and dotenv-expand, but it's not solving the issue I'm describing above I think. 

In none of my attempts, I was able to make `env.mjs` in `packages/api` to read relevant values from root `.env` file.

**Comment by juliusmarminge** [comment]
> packages/api doesn't have any build step.

it also doesn't run any code on it's own right? so the next app will load the envs for you.

check out create-t3-turbo where i do this:

https://github.com/t3-oss/create-t3-turbo/blob/main/apps/nextjs/package.json#L7
https://github.com/t3-oss/create-t3-turbo/blob/main/packages/auth/env.ts
https://github.com/t3-oss/create-t3-turbo/blob/main/apps/nextjs/next.config.js#L7

**Comment by gokaygurcan** [comment]
Hi again,

I followed this approach and ended up in a very weird place now. It's working as expected here, https://codesandbox.io/p/devbox/ecstatic-pascal-wxcffg and not on my local machine. I guess for the sake of this issue, we can say it's no longer an _issue_. But it's still weird to get two different results with the very same code. I'll keep looking if I have something else installed that causes this discrepancy. 

Thanks a lot, closing the issue now.

**Comment by gokaygurcan** [comment]
Update: eventually, i created a separate folder `packages/env` and moved everything under that. Instead of using it like `import { env } from @/env.mjs` i'm using it like `import { env } from '@something/env` now. Next step is to split it even further and import only relevant pieces if possible. 

After trying a few options, this felt like the best approach so far. Throwing it here, in case someone needs any guidance in the future.
