### ISSUE TITLE
Cannot find module '@t3-oss/env-nextjs' or its corresponding type declarations.ts(2307) for Version 0.9.2

### ISSUE THREAD

**Issue by valerius21** [t3-oss/t3-env#189]
Hi there!

Since the latest patch for version 0.9.2 my local instance and Vercel build pipeline do not seem to find the package, which results in a build error. 

I've found, that version 0.9.1 works perfectly fine. 

**Steps to reproduce**

Follow the documentation for Next.js

**Packages**

```json
{
  "name": "xxxx",
  "private": true,
  "scripts": {
    "dev": "next dev --turbo",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@mailchimp/mailchimp_marketing": "^3.0.80",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@t3-oss/env-nextjs": "0.9.2",
    "@upstash/ratelimit": "^1.0.1",
    "@vercel/analytics": "^1.1.3",
    "@vercel/edge": "^1.1.1",
    "@vercel/kv": "^1.0.1",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "date-fns": "^2.30.0",
    "framer-motion": "^11.0.3",
    "geist": "^1.2.2",
    "gray-matter": "^4.0.3",
    "next": "latest",
    "next-themes": "^0.2.1",
    "outstatic": "^1.0.0",
    "react": "18.3.0-canary-95ec12839-20240205",
    "react-dom": "18.3.0-canary-95ec12839-20240205",
    "remark": "^14.0.3",
    "remark-html": "^15.0.2",
    "tailwind-merge": "^2.2.1",
    "tailwindcss": "3.4.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.10",
    "@types/mailchimp__mailchimp_marketing": "^3.0.17",
    "@types/node": "^20",
    "@types/react": "18.2.55",
    "@types/react-dom": "18.2.19",
    "autoprefixer": "10.4.17",
    "eslint": "8.56.0",
    "eslint-config-next": "^14.1.0",
    "postcss": "8.4.35",
    "typescript": "5.3.3"
  }
}

```

**Comment by Re4GD** [comment]
Try:

```import { createEnv } from "@t3-oss/env-nextjs/dist";```
```import { createEnv } from "@t3-oss/env-core/dist";```

**Comment by akodkod** [comment]
Downgrading to v0.9.1 fixes the issue.

**Comment by deadcoder0904** [comment]
related issue: https://github.com/t3-oss/t3-env/issues/168

**Comment by juliusmarminge** [comment]
Needs reproduction repo. Likely a tsconfig option you have that doesnt support esm packages.

0.9 was a breaking change and we now only support esm + modern module resolutions (Node16+)

**Comment by ryota-murakami** [comment]
This is reproduction repo.
https://github.com/ryota-murakami/guestbook

**Comment by juliusmarminge** [comment]
Yup this is the issue: https://github.com/ryota-murakami/guestbook/blob/main/tsconfig.json#L13

Update that to use `Bundler` module resolution which supports reading `package.json#exports` conditions

**Comment by deadcoder0904** [comment]
using `"moduleResolution": "Bundler"` in `tsconfig.json` does fix the red-squiggly lines in vscode.

**Comment by juliusmarminge** [comment]
Considering this closed then, also added a note in docs about esm only. Reopen if you still have issues

**Comment by valerius21** [comment]
Thank you all! I will provide a reproducible next time :)

**Comment by ryota-murakami** [comment]
@juliusmarminge Thank you for sharing great links, that works!

**Comment by RussOakham** [comment]
I just stumbled across this issue too.

Maybe its worth adding a line into the README about this, so people can self-serve easier in future?

**Comment by juliusmarminge** [comment]
> Maybe its worth adding a line into the README about this, so people can self-serve easier in future?

Its in the docs

**Comment by ChiefORZ** [comment]
so whats the final resolution now? downgrading to 0.91?

**Comment by juliusmarminge** [comment]
> so whats the final resolution now? downgrading to 0.91?

no, swap `moduleResolution: node` to `moduleResolution: bundler` in  your tsconfig (or `NodeNext` if transpiling using tsc).

**Comment by CarlosZiegler** [comment]
Hey :) 
Get same error but in BUILD :
<img width="1375" alt="image" src="https://github.com/t3-oss/t3-env/assets/38855507/17a637c8-8f6f-4946-96f5-dd9d17d9c799">

<img width="392" alt="image" src="https://github.com/t3-oss/t3-env/assets/38855507/fd599734-ddf2-4eda-a20c-74361083c35a">

**Comment by AdrianBalcan** [comment]
@CarlosZiegler I've got the same!!

@juliusmarminge ... even if I have swapped `moduleResolution: node` to `moduleResolution: bundler`

**Comment by juliusmarminge** [comment]
Reopen if you can provide a reproduction. I cant help if you just say ”i got the same”.

**Comment by mmiszy** [comment]
> no, swap `moduleResolution: node` to `moduleResolution: bundler` in your tsconfig (or `NodeNext` if transpiling using tsc).

Unfortunately, this results in another error:

```
Cannot find module '@t3-oss/env-nextjs' or its corresponding type declarations.
  There are types at '/Users/……/node_modules/@t3-oss/env-nextjs/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)
```

Downgrading to 0.8 fixes the issue.

**Comment by juliusmarminge** [comment]
Locking this cause noone wants to provide a repro where i can actually help. If you have an issue and have made sure to use a supported module resolution and TS>5.0, reopen **with a reproduction repo**
