### ISSUE TITLE
Cannot find module '@t3-oss/env-nextjs' or its corresponding type declarations

### ISSUE THREAD

**Issue by palmjack** [t3-oss/t3-env#190]
After updating to v.0.9.2 I have this error `Cannot find module '@t3-oss/env-nextjs' or its corresponding type declarations`
I'm using pnpm v.8.15.1

**Comment by george1410** [comment]
+1

**Comment by george1410** [comment]
fix is to change `moduleResolutions` in my `tsconfig.json` to `bundler`

```json
"moduleResolution": "bundler"
```

**Comment by juliusmarminge** [comment]
t3-env is esm only since 0.9 so you must use a compatible module resolution (Bundler is recommended as suggested by George and [the docs](https://env.t3.gg/docs/core#install-dependencies))

**Comment by JulianKingman** [comment]
For those who this doesn't fix it, make sure you're using jiti version `1.x` (`1.21.7` is the latest that seems to work).

This is probably the same issue encountered by some people here: https://github.com/t3-oss/t3-env/issues/189

Added a PR with a minor docs change: https://github.com/t3-oss/t3-env/pull/298
