### ISSUE TITLE
feat: ability to specify unique values

### ISSUE THREAD

**Issue by hichemfantar** [t3-oss/t3-env#191]
What's the recommended approach for validating unique env vars?

my use case is application ports where i want to make sure multiple apps can't have the same port.

My proposal is a way to specify a prefix for unique values.

e.g. `PORT_ADMIN_DASHBOARD` (all env vars that start with `PORT_` must be unique)

I'm thinking a special env variable UNIQUE_VAR_PREFIXES that contains comma seperated prefixes that should be unique
e.g. UNIQUE_VAR_PREFIXES=PORT,OTHER_UNIQUE_PREFIX
when t3-env runs, it searches for vars with these prefixes and makes sure they're all unique

the vars below will throw an error
```
PORT_ADMIN_DASHBOARD=3000
PORT_CLIENT_DASHBOARD=3000
```

**Comment by juliusmarminge** [comment]
Should be solved with a `.refine` with #169

**Comment by juliusmarminge** [comment]
Can also do it today with just a check after the createEnv call, no?

```ts
const env = createEnv({
  server: {
    PORT_1: z.coerce.number(),
    PORT_2: z.coerce.number(),
  }
});

if (env.PORT_1 === env.PORT_2) {
  throw new Error("All ports must be unique");
}
```
