### ISSUE TITLE
Behavior Change when `clientPrefix` is empty

### ISSUE THREAD

**Issue by DanSnow** [t3-oss/t3-env#192]
### Issue Description

The behavior of the `clientPrefix` parameter in the `@t3-oss/env-core` library has changed, causing unexpected errors.

### Example

```javascript
import { createEnv } from '@t3-oss/env-core'
import { z } from 'zod'

const env = createEnv({
  isServer: false,
  clientPrefix: '',
  client: {
    FOO: z.string(),
  },
  runtimeEnvStrict: {
    FOO: 'FOO',
  },
})

console.log(env.FOO) // Throws error after upgrading to v0.9
```

In version 0.8, the provided code was functioning correctly. However, after upgrading to version 0.9, executing the same code results in the following error:

```
Attempted to access a server-side environment variable on the client
```

**Comment by juliusmarminge** [comment]
This is intended. If you want a client var without prefix use shared variables

**Comment by julius-retzer** [comment]
I'm running into same issue and using `shared` doesn't work. I see that there is this code in source 
```
   const isServerAccess = (prop)=>{
        if (!opts.clientPrefix)
            return true;
        return !prop.startsWith(opts.clientPrefix) && !(prop in shared.shape);
    }
```

So it means that if we have `clientPrefix: ''` it will never be accessible on client? I'm always getting the `Attempted to access a server-side environment variable on the client` if I put the variables in shared, `isServerAccess`  always returns true, even on client
