### ISSUE TITLE
Add note that path aliases will stop working if you use jiti

### ISSUE THREAD

**Issue by deadcoder0904** [t3-oss/t3-env#197]
I think most people use `@/app` instead of `../app` & they will face this error.

It should definitely be added to the docs otherwise everyone will keep opening the same issue.

For more context, see my comment -> https://github.com/t3-oss/t3-env/issues/180#issuecomment-1954165407

**Comment by juliusmarminge** [comment]
Docs uses relative path for the next config (you needed that even before jiti iirc).

I dont think we should expect eveyone to call out the shortcomings of other libs, the docs would become very daunting if we for example pointed out a bunch of "flaws" in Zod. That should live in their repo imo
