### ISSUE TITLE
Can't explicitly pass `clientPrefix` option using `nuxt`

### ISSUE THREAD

**Issue by dammy001** [t3-oss/t3-env#198]
```ts
import { createEnv } from '@t3-oss/env-nuxt'
import { z } from '@bunce/schema'

export const env = createEnv({
  clientPrefix: 'NUXT_',

  client: {
    NUXT_BASE_URL: z.string().min(1),
  },
  runtimeEnv: process.env,
})
```

This always make use of the default `NUXT_PUBLIC_`

**Comment by dammy001** [comment]
@juliusmarminge What if I don't want to add `PUBLIC_`? I just need `NUXT_`. This option `clientPrefix` should be exposed on userland.

**Comment by juliusmarminge** [comment]
I dont think you understand what clientPrefix means. It's the thing you prefix your variabler with if you want the value sent to client. NUXT_ doesnt do that, NUXT_PUBLIC_ does.

**Comment by dammy001** [comment]
@juliusmarminge Currently, without using `t3-env` my environment variables are prefixed with `NUXT_` without adding 'PUBLIC_', and it works fine, but adding this package will result in me changing my environment variables, which I really don't want to do.

**Comment by dammy001** [comment]
@juliusmarminge i get your point now

**Comment by juliusmarminge** [comment]
> Currently, without using t3-env my environment variables are prefixed with NUXT_ without adding PUBLIC_, and it works fine

Then those should go in the server object
