### ISSUE TITLE
How to augment `proccess.env` as well from `createEnv` output.

### ISSUE THREAD

**Issue by A7med3bdulBaset** [t3-oss/t3-env#200]
Is there a way to augment `NodeJS.ProccessEnv` by extending the `env` object without rewriting them one by one.

I've tried:

```ts
export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
  },
});

export type Env = typeof env
```
```ts
// env.d.ts
import type {Env} from "@/env";

declare global {
  namespace NodeJS {
    interface ProcessEnv extends Env {}
  }
}
```

I get errors in:
- `Env`: `Type alias 'Env' circularly references itself.ts(2456)` 
- `env`: `'env' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)`;

**Comment by juliusmarminge** [comment]
i dont think this is possible, as the error suggests it creates a circular reference.

what's the use case why you wanna do this?

**Comment by A7med3bdulBaset** [comment]
Got it, thanks

It was [a weird use case](https://x.com/A7med3bdulBaset/status/1761344924140577017?s=20)

going to close this

**Comment by A7med3bdulBaset** [comment]
Another trade-off is when using different name in `env.mjs` and `.env.local`

```ts
export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url().default("mysql://localhost:3306/db"),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_CONNECTING_STRING,
  },
});
```
