### ISSUE TITLE
Question: How to use with Expo

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [t3-oss/t3-env#203]
I saw that this library supports expo but does not know how to implement it.

**Comment by drazik** [comment]
I don't know if I'm doing this right, but here is what I did and is working:

- create a `env.ts` file with my environment variables schema:

```ts
import { createEnv } from "@t3-oss/env-core"
import { z } from "zod"

export const env = createEnv({
	clientPrefix: "EXPO_PUBLIC_",
	client: {
		EXPO_PUBLIC_GOOGLE_MAPS_API_KEY: z.string().min(1),
		EXPO_PUBLIC_API_BASE_URL: z.string().url(),
	},
	runtimeEnv: {
		EXPO_PUBLIC_GOOGLE_MAPS_API_KEY:
			process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY,
		EXPO_PUBLIC_API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
	},
})
```

- create a `.env` file that contains all my environment variables with fake values: this file is versioned as a reference for all the environment variables that should be filled in the project
- create a `.env.local` file that contains the environment variables with real values: this file in git ignored

Then use the `env` object

```ts
import { env } from "@/env"

env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY
```

I hope it helps!

**Comment by tyeetale** [comment]
also, I found a typescript issue when importing, so I added:

`"@t3-oss/env-core": ["./node_modules/@t3-oss/env-core/dist/index.d.ts"]`

to the `paths` section in `tsconfig.json`

**Comment by juliusmarminge** [comment]
> also, I found a typescript issue when importing, so I added:

That's most likely related to a bad moduleResolution setting in your tsconfig (or the expo base config you're extending from)
