### ISSUE TITLE
Installation steps do not work for net new Next.js Apps

### ISSUE THREAD

**Issue by dannyrb** [t3-oss/t3-env#213]
- https://create.t3.gg/en/usage/env-variables#adding-environment-variables
- https://env.t3.gg/docs/nextjs

I found the two sets of documentation above, and attempted to follow each of them in a net new `next.js` project with Typescript. Here are some issues I encountered:

- `next.config.js` does not build when using `import`/`export` syntax
- `import.meta.url` also requires module syntax
- One set of docs calls out "validating environment variables at runtime and buildtime", but the default setup does not seem to create buildtime checking
- If using `jiti` to add buildtime checking, next.config.js does not like module syntax, but client code does not like require / module.exports

**Comment by juliusmarminge** [comment]
Module syntax is based on you having `package.json#type` set to `module`. If you don't have that then you need to use the `.mjs` extension. This is true for any javascript file so I don't see why we should make this clear in our docs. 

Validating schema on build is done by importing the env file into your next config as shown here: https://env.t3.gg/docs/nextjs#validate-schema-on-build-(recommended)
