### ISSUE TITLE
Type Error: Type instatiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by Manokii** [t3-oss/t3-env#214]
Was wondering why typescript was very slow, then I saw this.
![240410_19h23m59s_screenshot](https://github.com/t3-oss/t3-env/assets/49423729/964a760a-d7d8-48c9-9f58-a6541d5fc025)

Versions:

- typescript@5.4.4
- @t3-oss/env-nextjs@0.9.2
- zod@3.22.4

Code Snippet
```ts
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    SECRET: z.string().min(1),
  },
  client: {},
});

```

**Comment by mwawrusch** [comment]
I ran into this too. We use bundler for moduleResolution (and can't change that). Happened when upgrading to the latest and greatest zod/t3-env

**Comment by AveshLutchman** [comment]
I have the same issue, using ModuleResolution as bundler, I have the latest zod + t3-env as well.
