### ISSUE TITLE
Next 14.2.1 support 

### ISSUE THREAD

**Issue by davimarcilio** [t3-oss/t3-env#218]
It's not working in the new version of next 14.2.2, I had to downgrade to version 14.1.0 to be able to use it

![image](https://github.com/t3-oss/t3-env/assets/104699555/7f71480e-1e6a-4d7d-824a-1c583833336c)

**Comment by juliusmarminge** [comment]
Failed to reproduce, please reopen with reproduction:

![Uploading CleanShot 2024-04-22 at 10.02.21@2x.png…]()

**Comment by durdenx** [comment]
The application fails when a required environment variable is set to an empty value, for example:
```
NEXT_PUBLIC_MY_PUBLIC_KEY=
```
This issue arises with the current Zod schema validation in `env.ts`:
```
NEXT_PUBLIC_MEILI_PUBLIC_KEY: z.string()
```
To resolve this, update the schema to allow optional values:
```
z.string().optional()
```

**Comment by juliusmarminge** [comment]
We have our `emptyStringAsUndefined` option - maybe Next decided to do something similar, idk

**Comment by davimarcilio** [comment]
In my case, everything was working when the version was lower than 14.2, after updating it stopped working, I did several tests to try to solve it but the only solution was to return the version
