### ISSUE TITLE
Add a step in docs to update tsconfig.json

### ISSUE THREAD

**Issue by hannanel100** [t3-oss/t3-env#22]
There should be another step in the docs to add "next.config.mjs" to the include property in tsconfig.

**Comment by juliusmarminge** [comment]
why is it necessary to include next.config.mjs for this to work?

you just import it there so that it validates on build - you don't need it to be typechecked.

is there sometihng im missing?

**Comment by hannanel100** [comment]
Nope. my bad...

**Comment by juliusmarminge** [comment]
although you probably should include it and check it for other reasons ;)
