### ISSUE TITLE
Getting `Unhandled Runtime Error` in nextjs

### ISSUE THREAD

**Issue by kingRayhan** [t3-oss/t3-env#23]
Here are my configs

```js
// source:  /src/env.mjs
import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const EnvironmentVariables = createEnv({
  clientPrefix: "NEXT_PUBLIC_",
  server: {},
  client: {
    NEXT_PUBLIC_API_REST_URL: z.string().url(),
    NEXT_PUBLIC_API_GRAPGQL_URL: z.string().url(),
    NEXT_PUBLIC_BOOKING_PAGE_URL: z.string().url(),
  },
  runtimeEnv: process.env, // or `import.meta.env`, or similar
});
```

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/7611746/234889893-6fd574bb-fefb-410d-ba20-ed9674e0f915.png">

**Comment by chungweileong94** [comment]
I believe you are using NextJS. In NextJS, you will have to specify each and every env variable that you are going to use in your app, it's due the way NextJS bundle the env variables. You can refer to doc here.
https://env.t3.gg/docs/nextjs

**Comment by kingRayhan** [comment]
Thanks @chungweileong94
