### ISSUE TITLE
Proposal to add extensions.json

### ISSUE THREAD

**Issue by Jacksondr5** [t3-oss/t3-env#243]
I started working on #169 and noticed that my editor was running Prettier as the default formatter on save, causing a lot of noisy changes.  After looking in the `.vscode/settings.json`, I noticed that the default formatter was set to "biomejs.biome", which I think references the [Biome extension](https://marketplace.visualstudio.com/items?itemName=biomejs.biome).  Problem is that I don't have this extension, so my editor is defaulting back to Prettier.

Would y'all be open to adding a [.vscode/extensions.json](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions) to prompt contributers to install the extensions that are already configured in `settings.json`?  Based on what I can gather from the `settings.json`, I think the `extensions.json` would be something like this:

```json
{
  "recommendations": ["biomejs.biome", "bradlc.vscode-tailwindcss", "unifiedjs.vscode-mdx"]
}
```
Not 100% sure about the mdx one, there are several options and I'm not sure which one `"mdx.experimentalLanguageServer": true` is referring to in the settings.

Happy to offer a PR for it.

**Comment by juliusmarminge** [comment]
sure
