### ISSUE TITLE
Issue with Loading Environment Variables in Docker Container

### ISSUE THREAD

**Issue by mehrabmp** [t3-oss/t3-env#244]
When I run my app using Docker, I get errors like "Invalid environment" for all my environment variables in the browser console. However, I'm certain that my environment variables are loaded into the container, as I have verified using the docker exec bash command.
The issue I noticed is that when I build my image with the .env file included, everything works fine. However, when I add .env to .dockerignore, I encounter this problem. It seems that the library only works with .env files and cannot get environment variables from the system or the Docker container.

**Comment by michielswaanen** [comment]
Experiencing the same issue after upgrading to Docker 4.30.0. I'm not sure if it's related to the upgrade.

**Comment by robodove** [comment]
Are you using turborepo to build/run ? 

https://turbo.build/repo/docs/reference/run#--env-mode-option

Turbo  --env-mode is strict by default (only env variables specified in the config are passed to the container)

Using 
```bash
$ turbo run build --env-mode loose
```

fixes this

**Comment by mehrabmp** [comment]
> Are you using turborepo to build/run ?
> 
> https://turbo.build/repo/docs/reference/run#--env-mode-option
> 
> Turbo --env-mode is strict by default (only env variables specified in the config are passed to the container)
> 
> Using
> 
> ```shell
> $ turbo run build --env-mode loose
> ```
> 
> fixes this

No I'm using create-t3-app

**Comment by robodove** [comment]
> > Are you using turborepo to build/run ?
> > https://turbo.build/repo/docs/reference/run#--env-mode-option
> > Turbo --env-mode is strict by default (only env variables specified in the config are passed to the container)
> > Using
> > ```shell
> > $ turbo run build --env-mode loose
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes this
> 
> No I'm using create-t3-app

that has nothing to do with deployment ?

Check your Dockerfile / Docker commands if it contains "turbo"..

**Comment by juliusmarminge** [comment]
I don't think this is related to this library.

You need to:

- for client side variables, the values have to be known at build-time as these are (most likely) statically replaced. So your Dockerfile must provide these (either from an env file or build args)
- for server variables, you don't want to inject these when you build the image. you instead want to provide these when starting the container. To make the build not fail when the variables aren't there, you can set the `skipValidation` option to something that identifies your build pipeline.
