### ISSUE TITLE
conditional environment variable based on environment

### ISSUE THREAD

**Issue by pondorasti** [t3-oss/t3-env#247]
Is it possible to create envs that are optional in `development` but required in `production`? I have a couple of tokens used for telemetry which are fine to be empty and no-op in dev, but production builds should fail if they are missing. 

I tried setting my env to an empty string, but local development blows up with _"Invalid environment variables"_ error.

```ts
// env.ts

import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  shared: {
    NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  },
  server: {
    ...
  },
  client: {
    NEXT_PUBLIC_TOKEN: z.string(),
    ...
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_TOKEN: process.env.NEXT_PUBLIC_TOKEN,
    ...
  },
  skipValidation: !!process.env.CI || !!process.env.SKIP_ENV_VALIDATION || process.env.npm_lifecycle_event === "lint",
})



// .env - development

NEXT_PUBLIC_TOKEN=""
```

Also, setting the token to a random value like `0x123` is not an option as this is automatically used by a 3rd party library which loads the env by itself. When the env is missing telemetry is disabled, and for non empty strings it will try collecting and sending events.

**Comment by jessekalil** [comment]
UP!

**Comment by juliusmarminge** [comment]
```ts
import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

const isProd = process.env.VERCEL_ENV === "production"; // or similar prod check

export const env = createEnv({
  server: {
    REQUIRED_IN_PROD: isProd ? z.string() : z.string().optional(),
  },
})
```

**Comment by pondorasti** [comment]
Thank you! 🤗
