### ISSUE TITLE
Error Missing "./dist" specifier in "@t3-oss/env-core" package

### ISSUE THREAD

**Issue by codeincolor** [t3-oss/t3-env#255]
The folder is there with the index file.  I tried adding the index file to the import path.  Same error.  Has anyone encountered this?  I havent seen it anywhere else. Here is the full error:

Error:   Failed to scan for dependencies from entries:
  D:/Users/Joe/source/repos/Psa.Cms/Web/index.html

  X [ERROR] Missing "./dist" specifier in "@t3-oss/env-core" package [plugin vite:dep-scan]

    src/constants/config.ts:2:26:
      2 │ import { createEnv } from "@t3-oss/env-core/dist"
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({

**Comment by juliusmarminge** [comment]
you should not import with `/dist` specifier. Just `import { createEnv } from "@t3-oss/env-core"`. Exports conditions will map to the correct file

**Comment by codeincolor** [comment]
![image](https://github.com/user-attachments/assets/44675c9a-0821-450d-b4cf-ff0335aedb2a)
Please image.  Thank you

**Comment by codeincolor** [comment]
I'm sorry but that doesnt tell much more than I already know.  I can see that its unsupported. What I dont understand is why.  I tried unistalling the package, then reinstalled the package (like any other). The installed directory structure is as expected. I would assume this would behave as any other dependancy.  
This looks to be a great app. Regrettably its not playing well with my react app. While this is frustrating, I do appreciate your responses.

**Comment by juliusmarminge** [comment]
Read the callout at the top: https://github.com/t3-oss/t3-env?tab=readme-ov-file#installation

You need a resolution that can read package.json#exports, e.g Bundler or NodeNext

**Comment by codeincolor** [comment]
Thank you!
