### ISSUE TITLE
Request - ability to pass z.object{...}) as .server, .client, .runtimeEnv of createEnv method

### ISSUE THREAD

**Issue by noahhai** [t3-oss/t3-env#256]
Allowing us to pass z.object instead of plain javascript object as each of these fields would allow us to call refine on the whole (e.g. server) object, and do validation that includes interaction between different environment variables/fields.

Willing to attempt a PR.

**Comment by chungweileong94** [comment]
Yes, this is actually the first step we want to achieve towards validator agnostics. https://github.com/t3-oss/t3-env/issues/6

**Comment by juliusmarminge** [comment]
Duplicate #169
