### ISSUE TITLE
Environment Variable Not Recognized in Docker Compose Setup

### ISSUE THREAD

**Issue by moreorover** [t3-oss/t3-env#284]
### Description

When running the development server locally using `bun dev`, the application successfully loads and displays the environment variable `NEXT_PUBLIC_APP_URL`.

However, when running the application using `docker compose up --build`, the app fails to load and reports that the `NEXT_PUBLIC_APP_URL` variable is not defined, even though it is specified in the `docker-compose.yml` file under the `environment` section.

I have verified that the `NEXT_PUBLIC_APP_URL` variable is indeed set inside the container by accessing it and running `echo $NEXT_PUBLIC_APP_URL`.

### Expected Behavior

The application should recognize the `NEXT_PUBLIC_APP_URL` environment variable and load correctly when using Docker Compose.

Reproducible: https://github.com/moreorover/env-repro

**Comment by Willem-Jaap** [comment]
How have you solved this?

**Comment by moreorover** [comment]
Any variable that starts with NEXT_PUBLIC_ is required at build time as the value of this variable gets inlined into the code at build time.

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

In my opinion its really odd one because this forces me to build two docker images with different domain names assigned to NEXT_PUBLIC_APP_URL for dev and production environments. Two builds are required for single application...

**Comment by moreorover** [comment]
> How have you solved this?

Any variable that starts with NEXT_PUBLIC_ is required at build time as the value of this variable gets inlined into the code at build time.

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

In my opinion its really odd one because this forces me to build two docker images with different domain names assigned to NEXT_PUBLIC_APP_URL for dev and production environments. Two builds are required for single application...
