### ISSUE TITLE
Bash code block icon bad positioning

### ISSUE THREAD

**Issue by esau-morais** [t3-oss/t3-env#34]
![image](https://user-images.githubusercontent.com/55207584/235328452-be242111-55c4-4739-8637-759ff2be4f7d.png)

**Comment by chungweileong94** [comment]
Looks like it only happens in dark mode, and only in production build. I can look into this.

**Comment by chungweileong94** [comment]
This should already be fixed in #32

**Comment by esau-morais** [comment]
> Looks like it only happens in dark mode, and only in production build. I can look into this.

I've got to reproduce the issue locally as well

![image](https://user-images.githubusercontent.com/55207584/235349865-d397ead0-6365-4ed9-bb88-97583a6bad32.png)

**Comment by chungweileong94** [comment]
You are right, you checked out the wrong commit. it's caused by the #32.

**Comment by chungweileong94** [comment]
You are right, I checked out the wrong commit. It's caused by the #32.
