### ISSUE TITLE
Consider server only apps

### ISSUE THREAD

**Issue by Adrien-P** [t3-oss/t3-env#44]
At the moment properties `clientPrefix` and `client` are required in `createEnv` options.  
These options are unnecessary for API only apps (express). 
For the `env-core` package it would be great to make these options optional.

**Comment by juliusmarminge** [comment]
if you dont have both sides this package is pure overhead for you.

you can just create a zod schema and parse it and be done with it. don't need the proxy logic that handles client/server boundary
