### ISSUE TITLE
maybe rename src/env.ts to src/t3Env.ts

### ISSUE THREAD

**Issue by JLarky** [t3-oss/t3-env#47]
I think instructions for Astro should include naming the file to a different name, because Astro already has `src/env.d.ts` file and something like `src/t3Ent.ts` (or t3_env, z_env, safe_env, valid_env, v_env, who knows) would be better. Then again, there's an option of trying to convince Astro to rename their file to `astro.d.ts` because I had so many issues with that file being named env :D

p.s. oh, right you need to convince Vite as well :) https://vitejs.dev/guide/env-and-mode.html#intellisense-for-typescript

<img width="801" alt="image" src="https://user-images.githubusercontent.com/7026/235811828-e7c3e8eb-a0e5-4273-8610-df183dbb7c48.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/7026/235811615-532bd147-915f-4b7f-8210-f5d1c9bec192.png">

**Comment by juliusmarminge** [comment]
done! stupid astro ;)

don't understand why frameworks generate these files... much better to put it in the `tsconfig.compilerOptions.types` field

**Comment by JLarky** [comment]
okay, when you say "done" :) what does that mean exactly? :) I don't see it changed anywhere yet :)

**Comment by juliusmarminge** [comment]
> okay, when you say "done" :) what does that mean exactly? :) I don't see it changed anywhere yet :)

https://github.com/t3-oss/t3-env/blob/main/examples/astro/src/t3-env.ts

**Comment by JLarky** [comment]
cool, thanks!
