### ISSUE TITLE
Question: What is the rationale for recommending variables validation on build?

### ISSUE THREAD

**Issue by lttr** [t3-oss/t3-env#58]
In the documentation there is a section called _Validate schema on build (recommended)_. I'm wondering why it should be recommended to do it at build time?

The reason to read environment variables at runtime (or when the server process starts) is to avoid doing a build for every environment. For commertial projects it is common to have multiple environments where an app is deployed to. It is quicker and more robust to build only once and use the resulting build artifact for all deployments to those environments.

How are you solving such situations?

Thank you for creating this library!

**Comment by intagaming** [comment]
Quoting the docs:

> Validate schema on build (recommended)
> 
> The steps required to validate your schema on build will vary from framework to framework, but you'll usually be able to import the env file in your configuration file, or in any file that's pulled in the beginning of the build process.
> 
> Note that some frameworks don't import their environment variables in their configuration file.

I think the instruction provided **also accidentally exactly** fits the description of "Validate schema at **runtime**".

For example, I'm using Astro, SSR enabled. By importing the env file like this in the `astro.config.ts` file...
```ts
await import("./src/env-validate");
```
... I was able to **also** validate the env vars at "runtime" (the `astro.config.ts` will be evaluated on server start).

Note the **also**.

In practice, the environment variables sneak in both at build time and at runtime.

`import.meta.env` (if you're using Vite) or `process` (if you're using anything else) is evaluated to a hardcoded object in the built JavaScript files. So even when you use `import.meta.env` on the server-side scripts, they will not change even if you modify the environment variables prior to running the server.

Right off the bat, you can see that your environment variables are indeed swept into the final JavaScript files at build time, before the server is even started. So unless you want your hardcoded items to go un-validated, you better trigger the validation at build time.

Now, when the server starts, the "runtime" begins. Here the `env-validate.ts` file is evaluated, but without any `import.meta.env` (or `process` with your bundler of choice) within it. They are all being hardcoded away by Vite (or something that you use). Here's the fun part: If you're using Next.js, [you might not be able to build once then load different environment variables into the built JS bundles](https://nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration). Astro can, via the `process` variable (which is different than `import.meta.env`).

Here's a sneak peek into my setup for a server-side environment variable in Astro:

```ts
  runtimeEnv: {
    API_HOST:
      (isServer ? fileEnv.API_HOST || process.env.API_HOST : undefined) ||
      import.meta.env.API_HOST,
    // ... more env
  },
```

Short explanation: `fileEnv` is `.env` files, loaded with the `loadEnv` Vite function, used in development for ease of `pnpm dev`; `process.env` is the runtime env vars (which you can dynamically change each time the server starts); `import.meta.env` is the fallback if there is nothing present **or the above script is evaluated on the client-side scripts**.

**Comment by intagaming** [comment]
^ I'll counter myself: Actually, even if you don't validate the hardcoded `import.meta.env`/`process.env` at build time, the runtime t3-env will still go and validate it (the hardcoded object). _By not validating on the build time, you are just allowing unvalidated variables to be hardcoded into your bundle._

You still can't dynamically change the hardcoded `import.meta.env`/`process.env` though (except Astro with `process.env`).

**Comment by lttr** [comment]
Ok, thanks, I can now understand the value of build time validation. It is useful to have some version of all variables during development for both build and run time, and you don't want to bundle anything that is not validated.

In times when it is necessary to skip validation, there is a way to do it, which I missed earlier. I is documented here: https://env.t3.gg/docs/customization

My specific use case is to build a Nuxt 3 application with some variables present all the time, while others are provided only in a docker container and are different for test, staging and production environments. Some of them might not be useful in development at all - for example a token for cookie consent widget provider.
