### ISSUE TITLE
Don't require destructure of process.env in Next.js

### ISSUE THREAD

**Issue by agusterodin** [t3-oss/t3-env#71]
This hasn't been released yet, but at a glance it appears as if Next is dropping the need to destructure process.env.

https://github.com/vercel/next.js/commit/aa91de56ce5110a9f6911b3d6cd694acad653e74

**Comment by chungweileong94** [comment]
Cool! We can probably mention this in the doc once it's released.

**Comment by juliusmarminge** [comment]
Awesome. Let's see when it's released to the public and make the appropriate changes after that!

**Comment by juliusmarminge** [comment]
> It is actually already release in 13.4.4.

Looks like client variables are still tree shaken away

**Comment by iduuck** [comment]
That's strange, because this PR is merged into 13.4.4 and vercel also announced in a blogpost (see #72).

**Comment by iduuck** [comment]
Didn't pull the branch, but just from looking at it I think you are not on 13.4.4: https://github.com/t3-oss/t3-env/blob/optional-runtime/pnpm-lock.yaml#L165-L167

**Comment by juliusmarminge** [comment]
I tried a canary release on a different repo

**Comment by juliusmarminge** [comment]
What do you think @iduuck - should we loosen up the strictness so that only the client keys are mandatory to destructure?

**Comment by chungweileong94** [comment]
> only the client keys are mandatory to destructure

Hmm... I don't really have a preference. But loosen up the strictness for server keys will allow us to do someting like
```ts
 runtimeEnv: {
    ...process.env,
    NEXT_PUBLIC_FOO: process.env.NEXT_PUBLIC_FOO,
 }
```
The only downside I can think of is that people who are on < 13.4.4 will have a slightly bad DX in terms of type safety.

**Comment by chungweileong94** [comment]
Just realize server keys weren't that strict before, until this #68. Can probably revert the `runtimeEnvStrict` type to open up the flxibility.

**Comment by iduuck** [comment]
Is there any reason why we are not splitting the `runtimeEnv` up into `clientEnv` and `serverEnv`? So that we could easily do something like 

```
clientEnv: { 
	NEXT_PUBLIC_FOO: process.env.NEXT_PUBLIC_FOO,
},
serverEnv: process.env,
```

OORRRR, even just use the process.env variable in our code, and just give the user the possibility to add custom things to the `serverEnv` attribute.

**Comment by iduuck** [comment]
However, DX is also not good, when doing something like, imo: 

```
 runtimeEnv: {
    ...process.env,
    NEXT_PUBLIC_FOO: process.env.NEXT_PUBLIC_FOO,
 }
```

I think, it's more straight forward to just keep it as is.

---

@juliusmarminge I would suggest just adding a hint to the docs stating that it is possible to use the `...process.env` way, but it's suggested to use the "traditional" way.

**Comment by chungweileong94** [comment]
> DX is also not good, when doing something like, imo:

Agree. At some point someone who is new to the codebase might refactor it into `runtimeEnv : process.env` and break things.

**Comment by juliusmarminge** [comment]
> Agree. At some point someone who is new to the codebase might refactor it into runtimeEnv : process.env and break things.

My local implementation were spreading the process.env internally, so it wouldn't be on the app level, but agree it could be confusing
