### ISSUE TITLE
Edge case when a variable is used by both client and server?

### ISSUE THREAD

**Issue by darwin403** [t3-oss/t3-env#73]
If i understand it right, the package assumes both the environment variables are mutually exclusive? What if I wish to use a variable in both the client and server side. For example, `NEXT_PUBLIC_GOOGLE_OAUTH2_CLIENT_ID`. 

Currently, redefining the variable seems to be the only way to go about. Is it possible to have a `shared` set of values?

**Comment by juliusmarminge** [comment]
the server can access client side variables so put it there 👍🏼
