### ISSUE TITLE
What files does it support? It doesn't work for me with .env.test

### ISSUE THREAD

**Issue by EgonBolton** [t3-oss/t3-env#76]
Does this library work only with `.env`?

I ask because Next.js [has support for different types of .env files](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables):

- .env
- .env.local
- .env.{production,development,test}
- .env.{production,development,test}.local

Particularly I have tried with `.env.test` but it does not work for me.

**Comment by juliusmarminge** [comment]
We don't load anything so it should work with any setup that loads the necessary object for you, in Next.js this would be the `process.env` so you can destructure from that.

So, any of the above should work just fine
