### ISSUE TITLE
❌ Attempted to access a server-side environment variable on the client

### ISSUE THREAD

**Issue by shahriyardx** [t3-oss/t3-env#79]
When I tried to use a server server environment variable in a serever component I get this error
```ts
Unhandled Runtime Error
Error: ❌ Attempted to access a server-side environment variable on the client
```

**Comment by chungweileong94** [comment]
Component without `"use client"` can be either client or server components, depending on how you import the component. 

For instance, if you try to import the component within a client component, it will render as a client component. In that case, you will not be able to use the server env. You can try to add `"use server"` on top of the component, to see if React complains about importing a "true" server component without client component.

If not, I would suggest you create a reproducible repo🙂

**Comment by shahriyardx** [comment]
So if i import a server component in a client component, that server component also becomes a client component? 

Will my environment variables leak if I use process.env.VAR rather than t3-env in this scenario

**Comment by chungweileong94** [comment]
> So if i import a server component in a client component, that server component also becomes a client component?

Yes, if you didn't specify both `use client` or `use server` directive for the component file, it will be server component by default, unless it's being imported after `use client` entry point.

> Will my environment variables leak if I use process.env.VAR rather than t3-env in this scenario

From what I can tell, neither will leak any server env. For `process.env.XXX`, it will show `undefined` on client-side. As for `t3-env`, it will throw error instead.

However, there are certain patterns that can leak the server env, which there is actually a discussion in #65.

**Comment by juliusmarminge** [comment]
> When I tried to use a server server environment variable in a serever component I get this error
> 
> ```ts
> Unhandled Runtime Error
> Error: ❌ Attempted to access a server-side environment variable on the client
> ```

Need more info. Mind sharing a repro?

**Comment by shahriyardx** [comment]
> 

Actually this is a private repo, which I can't share.
But what I can say is I used 'use server' on top snd process.env.VAR works fine but
env.VAR raises this error. 

I will try creating a dummy repo and share when I can.

**Comment by reubendrummond** [comment]
I'm getting the same error using `getStaticProps` in pages dir with Next 13.

**Comment by nixjs** [comment]
I also have the same problem. I use next13 with pages dir
<img width="1043" alt="image" src="https://github.com/t3-oss/t3-env/assets/23132483/30696546-03a1-4327-98a9-e1df199023dc">

**Comment by nixjs** [comment]
> I'm getting the same error using `getStaticProps` in pages dir with Next 13.
> 
> Edit: This is not due to this package but Next.js. Fixed by moving `getStaticProps` to another file and re-exporting it in the page.

I also had the same problem. Do I used under client.

**Comment by Apestein** [comment]
I'm getting this error when I import a fetcher function to both server and client component. If I redefine the function in the same file instead of importing it, then everything works fine.

**Comment by juliusmarminge** [comment]
Still need a repro

**Comment by Apestein** [comment]
> Still need a repro

Think I've manage to track it down. 
https://github.com/Apestein/env-bug-demo
![Screenshot (80)](https://github.com/t3-oss/t3-env/assets/107362680/44788935-26b0-4248-bc8e-b3e49adc698c)

In my [fetcher.ts file](https://github.com/Apestein/nextflix/blob/main/src/lib/fetchers.ts), I'm importing "db" which uses the env.DATABASE_URL variable. 
![Screenshot (81)](https://github.com/t3-oss/t3-env/assets/107362680/4e277438-f267-4bae-a3fb-5583f701de0f)

**Comment by chungweileong94** [comment]
> In my fetcher.ts file, I'm importing "db" which uses the env.DATABASE_URL variable.

The error is expected, as the `fetcher.ts` is being used in client component, which will also access the `env.DATABASE_URL`.

Ideally you want to separate both client and server code, to avoid server code injection in client code.

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment

**Comment by Apestein** [comment]
> > In my fetcher.ts file, I'm importing "db" which uses the env.DATABASE_URL variable.
> 
> The error is expected, as the `fetcher.ts` is being used/imported in client component, which will also access the `env.DATABASE_URL`.
> 
> Ideally you want to separate both client and server code, to avoid server code injection in client code.
> 
> https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment

Well no, because I'm only importing a specific function that doesn't contain any server code it doesn't make sense to have it work this way.

**Comment by juliusmarminge** [comment]
> Well no, because I'm only importing a specific function that doesn't contain any server code it doesn't make sense to have it work this way.

That's not how the bundler works, at least not the Next.js one. That's why some packages split their code up to multiple entrypoints, instead of exporting everything from the `index` one.

If it would work like you expect it to, packages like `client-only` or `server-only` wouldnt work.

Consider

```ts
import "server-only";
export function someServerOnlyFunction() { ... }
export function someUtilityFunction() { ... }
```

How would the server-only package work if we would want to allow the utility function to be importable on both ends? The only way this works is to split the code up and put the utility function in a separate file.

**Comment by chungweileong94** [comment]
> I'm only importing a specific function that doesn't contain any server code 

I understand what you mean, but unfortunately that's not how it works. 

Even when you just import one of the functions from the file, all the code from the same file will still be executed or maybe bundle (it depends) together with client component. At least not by default, there might be a why, but not that I know of.

Especially when the `env.DATABASE_URL` is being called at the root of the `fetcher.ts`.

**Comment by chungweileong94** [comment]
In NextJS App Router, it will only exclude server code from client code in two conditions:

- The function or the file is not being used as part of client code
- the function or the file is flagged with `'use server'` directive.

Tree shaking might help🤷‍♂️(correct me if I'm wrong), but it's still pretty dangerous to have both server and client code live in one file, as you might accidentally leak your server secret values to the client code.

You can try ignore the error and try build the code, you might see that the database url is leak in one of the bundled client code.

**Comment by Apestein** [comment]
> > Well no, because I'm only importing a specific function that doesn't contain any server code it doesn't make sense to have it work this way.
> 
> That's not how the bundler works, at least not the Next.js one. That's why some packages split their code up to multiple entrypoints, instead of exporting everything from the `index` one.
> 
> If it would work like you expect it to, packages like `client-only` or `server-only` wouldnt work.
> 
> Consider
> 
> ```ts
> import "server-only";
> export function someServerOnlyFunction() { ... }
> export function someUtilityFunction() { ... }
> ```
> 
> How would the server-only package work if we would want to allow the utility function to be importable on both ends? The only way this works is to split the code up and put the utility function in a separate file.

Ok, I see. I don't know anything about the bundler. Thanks for clarifying.
