### ISSUE TITLE
bug/qol: fix lockfile out of sync w/ changesets

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/t3-env#8]
This is annoying having to sync manually after each release

<img width="1213" alt="CleanShot 2023-04-25 at 12 52 54@2x" src="https://user-images.githubusercontent.com/51714798/234255634-f0d8e8e7-a827-41e0-b2b0-d28b1a0b7e12.png">

**Comment by rexfordessilfie** [comment]
Hi @juliusmarminge! Thanks for your work on this project. On this issue I wanted to clarify a desired approach. Which of these options if any would be most appropriate or which other solutions do you have in mind?
* update and commit pnpm-lock during CI
* check for out-of-date pnpm-lock during CI + block merge if not up to date

**Comment by juliusmarminge** [comment]
It's a problem in changeset that should be handled automatically but for some reason isn't...

https://github.com/changesets/changesets/issues/421
