### ISSUE TITLE
How to avoid SCREAMING_SNAKE_CASE throughout codebase

### ISSUE THREAD

**Issue by ravinggenius** [t3-oss/t3-env#82]
I'm new to `t3-env`, but it's similar to hand-rolled solutions I've used in the past. The "standard" way to define a basic config file seems to be something like the following:

```typescript
// config.ts

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const config = createEnv({
	runtimeEnv: {
		DATABASE_URL: process.env.DATABASE_URL,
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH:
			process.env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH
	},
	client: {
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive())
	},
	server: { DATABASE_URL: z.string().url() }
});

export default config;
```

... which could be used like:

```typescript
// client.ts

import config from "./config";

console.log(config.NEXT_PUBLIC_PASSWORD_MIN_LENGTH);
```

... or:

```typescript
// server.ts

import config from "./config";

console.log(config.DATABASE_URL);
```

My problem with this is 1) my code is now yelling at me everywhere I use env configuration *and* 2) I constantly have to remember Next's client-safe prefix, even when I use the value on the server. It's forcing me to pollute my code.

What I would prefer is the following:

```typescript
// config.ts

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const config = createEnv({
	runtimeEnv: {
		databaseUrl: process.env.DATABASE_URL,
		passwordMinLength: process.env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH
	},
	client: {
		passwordMinLength: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive())
	},
	server: { databaseUrl: z.string().url() }
});

export default config;
```

This actually seems to work fine for server-only values. I even don't get any type errors when reading the value `config.passwordMinLength`. Autocomplete and IDE type inspections also behave as expected. However the client config isn't happy because the `client.passwordMinLength` key isn't prefixed with `NEXT_PUBLIC_`. This type error cascades into `runtimeEnv.passwordMinLength`, which isn't recognized as a valid property name.

**Comment by ravinggenius** [comment]
One potential way to address my issues is to use `createEnv` to define a temporary variable, then use that to manually populate an exported variable with the names I actually want:

```typescript
// config.ts

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const env = createEnv({
	runtimeEnv: {
		DATABASE_URL: process.env.DATABASE_URL,
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH:
			process.env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH
	},
	client: {
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive())
	},
	server: { DATABASE_URL: z.string().url() }
});

const config = {
	databaseUrl: env.DATABASE_URL,
	passwordMinLength: env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH
};

export default config;
```

I don't love this because it's verbose. I'm also certain I'm going to add something to `env` and forget to add it to `config` at some point. Is there a better solution? Are there any subtle gotchas with approach?

**Comment by ravinggenius** [comment]
I didn't have a chance to actually execute the code I wrote above when I wrote it. Of course I was immediately reminded that Next throws when the client tries to read non-prefixed environment variables. This is why (I assume) the docs show `export const env = ...`, while `createEnv()` returns a `Proxy` to lazy-read the actual values. This enables the same config file to be used on both the server and client. As long as the client doesn't attempt to read a server-only value, Next doesn't throw "Unhandled Runtime Error: Attempted to access a server-side environment variable on the client".

This `Proxy` wrapper is really cool, but I still have the problems I mentioned above. Further I cannot work around the naming, at least for client-readable values, without reverting to using two files. This is similar to the approach I landed on before when I was hand-rolling environment getters.

```typescript
// config-client.ts

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const env = createEnv({
	runtimeEnv: {
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH:
			process.env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH
	},
	client: {
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive())
	}
});

export const passwordMinLength = env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH;
```

```typescript
// config.ts

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export * from "./config-client";

const env = createEnv({
	runtimeEnv: {
		DATABASE_URL: process.env.DATABASE_URL
	},
	server: { DATABASE_URL: z.string().url() }
});

export const databaseUrl = env.DATABASE_URL;
```

All in all this is still an improvement as I don't have to maintain an internal library anymore. It is unfortunate that I still need to be careful about importing the correct config file into client environments. I would prefer to have a single config file to maintain instead of two. Still I'm able to maintain my "friendly" names throughout my codebase. (I'm currently coding on a Chromebook. These machines don't have a Caps Lock key, so typing in SCREAMING_SNAKE_CASE in a pain. My aesthetic concerns listed above would still hold regardless.)

---

To cut to the chase, could the `NEXT_PUBLIC_*` naming requirement for client config be reconsidered?

**Comment by juliusmarminge** [comment]
> To cut to the chase, could the NEXT_PUBLIC_* naming requirement for client config be reconsidered?

It could, if more people request this. The thought process behind this is that it should be easily recognizable that you're accessing server or client stuff, and that's why we enforce the naming.

We could perhaps add a flag that let's you opt-out of this validation, such as 

```ts
const env = createEnv<"UNSAFE_NAMING_CONVENTIONS">({
  client: {
    foobar: z.string()
  },
  // ...
});
```

although I'm not sure how the implementation would look like to support that 🤔

**Comment by watch-janick** [comment]
@ravinggenius Hey, I was wondering how did you manage to make your `.ts` config file for t3 env working with NextJS config file?

When I tried to use `next.config.ts` I ran into errors (don't remember right now) and had to stay with `.mjs`.

**Comment by juliusmarminge** [comment]
> @ravinggenius Hey, I was wondering how did you manage to make your `.ts` config file for t3 env working with NextJS config file?
> 
> 
> 
> When I tried to use `next.config.ts` I ran into errors (don't remember right now) and had to stay with `.mjs`.

You can't import ts in Next config since they dont transpile the config or anything. Must be javascript

**Comment by ravinggenius** [comment]
@watch-janick I don't have my computer in front of me right now, but I think I ended up going with `.mjs` for env config and Next config. It's not ideal, but TypeScript still infers the correct types. I'll double-check when I can get back on.

**Comment by ravinggenius** [comment]
Yeah I ended up with `*.mjs` files.

```typescript
// src/library/_/config-public.mjs

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const env = createEnv({
	runtimeEnv: {
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH:
			process.env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH
	},
	client: {
		NEXT_PUBLIC_PASSWORD_MIN_LENGTH: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive())
	}
});

export const passwordMinLength = env.NEXT_PUBLIC_PASSWORD_MIN_LENGTH;
```

```typescript
// src/library/_/config.mjs

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export * from "./config-public.mjs";

const env = createEnv({
	runtimeEnvStrict: {
		DATABASE_URL: process.env.DATABASE_URL,
		NODE_ENV: process.env.NODE_ENV,
		PASSWORD_SALT_ROUNDS: process.env.PASSWORD_SALT_ROUNDS,
		SESSION_COOKIE_PATH: process.env.SESSION_COOKIE_PATH,
		SESSION_COOKIE_SAME_SITE: env.SESSION_COOKIE_SAME_SITE,
		SESSION_MAX_AGE_SECONDS: process.env.SESSION_MAX_AGE_SECONDS,
		SESSION_NAME: process.env.SESSION_NAME,
		SESSION_SECRET: process.env.SESSION_SECRET
	},
	server: {
		DATABASE_URL: z.string().url(),
		NODE_ENV: z.enum(["development", "production", "test"]),
		PASSWORD_SALT_ROUNDS: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive()),
		SESSION_COOKIE_PATH: z.string().refine((path) => path.startsWith("/")),
		SESSION_COOKIE_SAME_SITE: z.enum(["lax", "none", "strict"]),
		SESSION_MAX_AGE_SECONDS: z
			.string()
			.transform((n) => Number.parseInt(n, 10))
			.pipe(z.number().positive()),
		SESSION_NAME: z.string(),
		SESSION_SECRET: z.string().minLength(32)
	}
});

export const isDevelopment = env.NODE_ENV === "development";

export const isProduction = env.NODE_ENV === "production";

export const isTest = env.NODE_ENV === "test";

/**
 * Postgres database connection URL. Can point to a connection pool
 */
export const databaseUrl = env.DATABASE_URL;

export const passwordSaltRounds = env.PASSWORD_SALT_ROUNDS;

export const sessionCookieOptions = {
	httpOnly: true,
	path: env.SESSION_COOKIE_PATH,
	sameSite: env.SESSION_COOKIE_SAME_SITE,
	secure: isProduction
};

export const sessionMaxAgeSeconds = env.SESSION_MAX_AGE_SECONDS;

export const sessionName = env.SESSION_NAME;

export const sessionSecret = env.SESSION_SECRET;
```

```typescript
// next.config.mjs

import "./src/library/_/config.mjs";

/** @type {import('next').NextConfig} */
const nextConfig = {
	experimental: {
		serverActions: true
	}
};

export default nextConfig;
```

**Comment by ravinggenius** [comment]
I needed to keep two files because I'm eager-evaluating the `Proxy`s that `@t3-oss/env-nextjs` returns with `createEnv()`.
