### ISSUE TITLE
Breaks the checks upon the symbols combination in env variable

### ISSUE THREAD

**Issue by nike1v** [t3-oss/t3-env#83]
I'm facing the issue where it completely breaks if any of the env variables have $% combination of symbols.
In case where it is present, all other enviroment variables became undefined too. 
Am I doing something wrong, or it's just a bug?
Thanks.

**Comment by juliusmarminge** [comment]
can you post a repro?

also can you try directly accessing the values on `process.env` and see if they are defined there
