### ISSUE TITLE
fix: make options type shareable between packages

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/t3-env#9]
i ran into some weird inference issues when the next.js package extended the core package options type - should be fixed to avoid a bunch of duplications

**Comment by chungweileong94** [comment]
@juliusmarminge Mind if I ask what sort of the issue you are running into? 
I was able to reuse the options type from the core in NextJS package without muting the TS error, and I'm not sure if we are talking the same thing.

**Comment by chungweileong94** [comment]
Here's what I did, https://github.com/chungweileong94/t3-env/blob/main/packages/nextjs/index.ts

**Comment by juliusmarminge** [comment]
> @juliusmarminge Mind if I ask what sort of the issue you are running into? 
> 
> I was able to reuse the options type from the core in NextJS package without muting the TS error, and I'm not sure if we are speaking the same thing. 

I think in particular it was the prefix which stopped erroring, so I could put any key in the client object without any errors
