### ISSUE TITLE
Feature request: Allow loading seperate .env file based on node environment

### ISSUE THREAD

**Issue by benediktms** [t3-oss/t3-env#98]
This would be very useful for being able to load e.g. a seperate database url during testing

**Comment by chungweileong94** [comment]
As of now, t3-env only handle the env validation. 

With that said, it's depends on which framework you are using and how they handle the env loading, for instance:

- NextJS - https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#default-environment-variables
- ViteJS - https://vitejs.dev/guide/env-and-mode.html#modes

**Comment by benediktms** [comment]
Understood, thanks!
