### ISSUE TITLE
Vitest with @t3-oss/env-nextjs

### ISSUE THREAD

**Issue by teddybee** [t3-oss/t3-env#99]
I would like to test with Vitest and NextJS, unfortunately there are some errors:
```
Error: Invalid environment variables
 ❯ onValidationError node_modules/@t3-oss/core/index.ts:184:13
 ❯ h node_modules/@t3-oss/core/index.ts:196:12
 ❯ Module.P node_modules/@t3-oss/env-nextjs/index.ts:73:10
 ❯ env.mjs:4:20
      2| import { z } from "zod";
      3|
      4| export const env = createEnv(
```
As far as I understand I need to ovverride the default VITE_ env prefix somewhere in the vitest.config.js.
```
export default defineConfig({
  plugins: [react()],
  test: {
    setupFiles: '@t3-oss/env-nextjs', // here
  },
```
Could somebody help me how to set properly the setupFiles row with t3-env?

**Comment by chungweileong94** [comment]
Have you try to define the `envPrefix` option in `vite.config.ts`?
https://vitejs.dev/config/shared-options.html#envprefix

**Comment by chungweileong94** [comment]
@teddybee Mind if you can provide a simple repro🙂

**Comment by teddybee** [comment]
I got it, this solved the SSR env problem as well:
```
export default defineConfig({
  plugins: [react()],
  envPrefix: "NEXT_PUBLIC_",
 
  test: {
    environment: "node",
    setupFiles: 'dotenv/config',
  },
```
